name: CI

on: [push, pull_request]

jobs:
  test:
    name: Node.js v${{ matrix.nodejs }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        nodejs: [16.x, 17.x, 18.x]
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.nodejs }}
        
    - name: Install pnpm
      run: npm install -g pnpm@latest

    - name: Install
      run: pnpm install

    - name: Test
      run: pnpm test
